# Generated by Django 4.0.2 on 2022-03-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mundialClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paises', models.CharField(max_length=30)),
                ('pj', models.IntegerField()),
                ('g', models.IntegerField()),
                ('e', models.IntegerField()),
                ('p', models.IntegerField()),
                ('gf', models.IntegerField()),
                ('gc', models.IntegerField()),
                ('dg', models.IntegerField()),
                ('pts', models.IntegerField()),
            ],
        ),
    ]
