# Generated by Django 4.0.2 on 2022-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacionMundial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mundialclasificacion',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
